before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
    - wget http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz
    - tar -zxf android-sdk_r22.2.1-linux.tgz
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - echo yes | android --silent update sdk --filter platform-tools,android-17,sysimg-17 --no-ui --force

language:
    - java


script: "./gradle cleanFlow testAll buildAll -i -s"